device: cuda:0
save_path: checkpoint/best_model.pt
comet: True
comet_config:
  project_name: dl-bhw2
random_seed: 42

vocab:
  min_count: 5

train:
  num_epochs: 20
  mode: dual
  beam_size: 1
  max_new_tokens: 80
  max_grad_norm: 1.0
  label_smoothing: 0.05
  bleu_max_batches: 7
  bleu_max_samples: null
  dual:
    reverse_prob_scheduler:
      name: cosine
      k: 0.1

model:
  name: TRANSFORMER
  d_model: 512
  n_heads: 8
  n_layers: 6
  d_ff: 2048
  dropout: 0.15
  max_src_len: 100
  max_tgt_len: 100

optimizer:
  name: AdamW
  lr: 0.00015
  weight_decay: 0.0001

scheduler:
  name: transformer_warmup
  warmup_steps: 2000

train_dataset:
  source_path: bhw2-data/data/train.de-en.de
  target_path: bhw2-data/data/train.de-en.en

val_dataset:
  source_path: bhw2-data/data/val.de-en.de
  target_path: bhw2-data/data/val.de-en.en

test_dataset:
  source_path: bhw2-data/data/test1.de-en.de

train_loader:
  batch_size: 32
  shuffle: true
  pin_memory: true
  num_workers: 2

reverse_train_loader:
  batch_size: 32
  shuffle: true
  pin_memory: true
  num_workers: 2

val_loader:
  batch_size: 32
  shuffle: false
  pin_memory: true
  num_workers: 2

test_loader:
  batch_size: 32
  shuffle: false
  pin_memory: true
  num_workers: 2

test_output:
  path: predictions/test1.translations.en
  max_len: 80

inference:
  checkpoint_path: checkpoint/best_model.pt
  output_path: predictions/test1.translations.en
  max_len: 90
  beam_size: 5
  replace_unk_with_attn_copy: True

checkpoint_averaging:
  enabled: True
  num_last: 5
  dir: checkpoint/avg
  metric: loss
  reset_on_start: true
