device: cuda:0
save_path: checkpoint/best_model.pt
comet: True
comet_config:
  project_name: dl-bhw2
random_seed: 42

train:
  num_epochs: 8
  beam_size: 4
  max_new_tokens: 80
  max_grad_norm: 1.0

model:
  name: TRANSFORMER
  d_model: 512
  n_heads: 8
  n_layers: 3
  d_ff: 2048
  dropout: 0.1
  max_src_len: 256
  max_tgt_len: 256

optimizer:
  name: AdamW
  lr: 0.001
  weight_decay: 0.0

scheduler:
  name: CosineAnnealingLR
  eta_min: 0.00001
  T_max: 8

train_dataset:
  source_path: bhw2-data/data/train.de-en.de
  target_path: bhw2-data/data/train.de-en.en

val_dataset:
  source_path: bhw2-data/data/val.de-en.de
  target_path: bhw2-data/data/val.de-en.en

test_dataset:
  source_path: bhw2-data/data/test1.de-en.de

train_loader:
  batch_size: 32
  shuffle: true
  pin_memory: true
  num_workers: 2

val_loader:
  batch_size: 32
  shuffle: false
  pin_memory: true
  num_workers: 2

test_loader:
  batch_size: 32
  shuffle: false
  pin_memory: true
  num_workers: 2

test_output:
  path: predictions/test1.translations.en
  max_len: 80

inference:
  checkpoint_path: checkpoint/best_model.pt
  output_path: predictions/test1.translations.en
  max_len: 80
